site_name: Refinery Yield Optimizer
site_description: ML system for refinery yield optimizer
repo_url: https://github.com/kcabrera-oil-gas/refinery-yield-optimizer
site_author: Kelvin J Cabrera

theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.instant
    - navigation.top

nav:
  - Home: index.md
  - API: api.md
  - Models: models.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
